### ISSUE TITLE
Package isn't published on PyPi

### ISSUE THREAD

**Issue by NathHorrigan** [tr11/wagtail-graphql#3]
Library looks awesome but I can't actually install it in my project:
```
$ pip3 install wagtail-graphql
Collecting wagtail-graphql
  Could not find a version that satisfies the requirement wagtail-graphql (from versions: )
No matching distribution found for wagtail-graphql
```

Installing via git also doesn't work because there is no `setup.py`: 
```
$ pip3 install git+https://github.com/tr11/wagtail-graphql
Collecting git+https://github.com/tr11/wagtail-graphql
  Cloning https://github.com/tr11/wagtail-graphql to /tmp/pip-req-build-wp0q110w
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/vagrant/.virtualenvs/torchbox/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-wp0q110w/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-wp0q110w/
```

**Comment by tr11** [comment]
You're right -- I haven't published it to PyPi.  Will do it in the next couple of days.

**Comment by sany2k8** [comment]
package is available on pypi but not able to install it, it is showing,

**ERROR: Could not find a version that satisfies the requirement wagtail-graphql (from versions: none)**
